Implement pgtle.create_shell_type function to support shell type creation in pg_tle
aws/pg_tle pull request #205
Opened 2023-06-08 20:38 UTC by lyupan

Description of changes:
Implemente pgtle.create_shell_type function:
1. pgtle.create_shell_type requires two arguments: namespace and type name;
2. pgtle.create_shell_type can only be executed by pgtle_admin and superuser;

This is the first commit to support custom base types in pg_tle.

Test:
Regression test is added in pg_tle_datatype.sql. Locally running the test and verified that it succeeded in pg15 and pg16.

By submitting this pull request, I confirm that my contribution is made under the terms of the Apache 2.0 license.

2023-06-09 14:38 UTC, formalLogicGirl commented on src/datatype.c
> +    CHECK_CAN_SET_ROLE(GetUserId(), tleadminoid);
nit : can we make the whitespace formatting consistent

2023-06-09 14:42 UTC, formalLogicGirl commented on test/expected/pg_tle_datatype.out
> + lyup
this will not match for other people running the test and fail the test, right?

2023-06-09 15:41 UTC, jkatz commented on src/datatype.c
> +    CHECK_CAN_SET_ROLE(GetUserId(), tleadminoid);
We may need a `pgformatter` run -- it's available in the PostgreSQL repo.

2023-06-09 15:49 UTC, jkatz approved these changes

2023-06-09 15:49 UTC, jkatz commented on src/datatype.c
> +	tuple = SearchSysCache1(AUTHNAME, CStringGetDatum("pgtle_admin"));
`pgtle_admin` should be defined in a constant. Unsure if it should be in `constants.h` or `tleextension.h` -- leaning towards `tleextension.h` as it contains names specific to the TLE extension itself, though maybe those need to be moved to `constants.h`

2023-06-09 15:49 UTC, jkatz commented on src/datatype.c
> +	PG_RETURN_BOOL(false);
I would opt to return an error if we're unable to create the shell type. That way, if this is in a transaction, it will fail.

2023-06-09 15:49 UTC, jkatz commented on src/datatype.c
> +	}
See comment below -- we could have a similar pattern to other functions, e.g. `create_shell_type` which will error if the type already exists, and `create_shell_type_if_not_exists` which will return `false` if it exists. Example:

https://github.com/aws/pg_tle/blob/main/docs/03_managing_extensions.md#pgtleregister_feature_if_not_existsproc-regproc-feature-pg_tle_features

2023-06-09 15:53 UTC, jkatz requested changes
Good start! Please see previous review for the requested changes / comments.

2023-06-09 18:43 UTC, formalLogicGirl commented on src/datatype.c
> +	}
Since we are mirroring the Postgres CREATE TYPE wouldn't it be good to keep the behavior similar? In Postgres, if the type already exists then an error is generated. I was thinking we want to do the same here.

2023-06-09 20:49 UTC, lyupan commented on pg_tle--1.0.1--1.0.4.sql
> +
Done. Added a new version 1.0.5

2023-06-09 20:49 UTC, lyupan commented on src/datatype.c
> +    CHECK_CAN_SET_ROLE(GetUserId(), tleadminoid);
Done, run `pg_indent`.

2023-06-09 20:50 UTC, lyupan commented on test/expected/pg_tle_datatype.out
> + lyup
Ah, this was a mistake. Fixed.

2023-06-09 20:51 UTC, lyupan commented on src/datatype.c
> +	tuple = SearchSysCache1(AUTHNAME, CStringGetDatum("pgtle_admin"));
Defined a new constant `PG_TLE_ADMIN`.

2023-06-09 20:53 UTC, lyupan commented on src/datatype.c
> +	PG_RETURN_BOOL(false);
Yeah, that makes sense. Updated the code.

2023-06-09 20:56 UTC, lyupan commented on src/datatype.c
> +	}
Add a new create_shell_type_if_not_exists function:
`create_shell_type` now fails (report error) if the type already exists;
`create_shell_type_if_not_exists` returns false if it exists.

2023-06-09 20:59 UTC, lyupan commented
Thanks for the review! Made some updates based on the comments, please take another look.

2023-06-09 23:07 UTC, JohnHVancouver commented on src/datatype.c
> +	tuple = SearchSysCache1(AUTHNAME, CStringGetDatum("pgtle_admin"));
I think you can simplify this by just calling `get_role_oid`  and don't have to re-implement

2023-06-09 23:07 UTC, JohnHVancouver commented on src/datatype.c
> +	}
OOC when would a user call one over the other?

2023-06-13 17:22 UTC, formalLogicGirl commented on src/datatype.c
> +	}
Thats a great question. Its not clear to me that there is a very compelling use case for `create_shell_type_if_not_exists`. In Postgres, there isn't a similar function. In pg_tle, by design, we want to prevent leaving behind a shell type when a custom base type created in pg_tle gets successfully dropped. So there is not supposed to be a scenario where a shell type is left behind, and if that were the case, it seems like an error message informing the user would be helpful. Shell types also can't be shared between different custom base types, so no expectation of the shell type having been already created for some other reason. So then it comes down to whether the user wants the create function to not error under any circumstance, in which case they should use `create_shell_type_if_not_exists`. Is that a significant enough requirement that we need this function for?

2023-06-13 18:26 UTC, formalLogicGirl commented on src/datatype.c
> +	}
Not failing the transaction may be the significant use case that justifies the if_not_exists form of this function. Okay.

2023-06-13 18:28 UTC, formalLogicGirl approved these changes
Looks mostly good to me. I think its good to merge and work on the next functions. We can revisit if there are any updates we still need. I think you've already addressed all the comments raised so far.

2023-06-13 18:56 UTC, merged