Implement create_base_type API.
aws/pg_tle pull request #206
Opened 2023-06-16 18:56 UTC by lyupan

Description of changes:

pgtle_admin can run create_base_type API to create a new base type (providing I/O funcs and other required arguments) in pg_tle.

User-defined input function must accept TEXT and return BYTEA, we make an C-version input function that accepts CSTRING and returns the new TYPE, the C-version input function will be used internally to create the type; inside the C-version input function, we find the user-defined input function and execute it. A dependency between C-version function and user-defined function is recorded in pg_depend, so that `DROP FUNC ... CASCADE` can work as expected.

Output function works in a similar way as the input function.

`create_base_type` implementation is similar to `DefineType` https://github.com/postgres/postgres/blob/master/src/backend/commands/typecmds.c#L148, except pg_tle specific part.

Future improvements:
1. The newly-created type can set to NULL value, and it reads/outputs NULL without invoking the user-defined I/O functions. In Postgres `CREATE TYPE` experience, input function is still called when reading a NULL input value, but it must still return NULL; output function are not invoked for NULL values. We may want to align the behavior for NULL values, but it seems to be a minor detail for now.
2. Other base type features (e.g. send/receive functions, storage, collation) are not supported in this version.

By submitting this pull request, I confirm that my contribution is made under the terms of the Apache 2.0 license.

2023-06-17 19:05 UTC, jkatz commented on src/datatype.c
> +#if PG_VERSION_NUM >= 140000
Similarly -- is there a way to put this into `compatibility.h` or the like, so there is only one call needed here?

2023-06-19 23:37 UTC, lyupan commented on src/datatype.c
> +	Oid			typeoid;
It seems both `typeOid` and `typoid` are used https://github.com/postgres/postgres/blob/0d369ac650041862ed5006885160f36d24b224a4/src/backend/commands/typecmds.c#LL1340C2-L1340C15
```
Oid			typeOid;
```

```
Oid			typoid;
```

s/typeoid/typeOid because `typeOid` seems more common

2023-06-19 23:40 UTC, lyupan commented on src/datatype.c
> +	char	   *probin = get_probin(fcinfo->flinfo->fn_oid);
This code alignment is actually preferred by `pgindent`. (I tried to manually adjust it, but pgindent will change it back to this format)

2023-06-19 23:41 UTC, lyupan commented on src/datatype.c
> +#endif
Good idea! Fixed.

2023-06-19 23:50 UTC, lyupan commented on src/datatype.c
> +#if PG_VERSION_NUM >= 140000
I don't see an elegant way to put this into `compatibility.h`. `TypeCreate(...)` is used twice, one for base type creation, one for array type creation, a few arguments are different between the two calls. Also, `TypeCreate` requires many arguments which is already error-prone ... Let me know if you have a better idea on this.

2023-06-23 17:31 UTC, jkatz reviewed
I think we need to ensure we have a check that the user-provided function is immutable.

2023-06-23 17:31 UTC, jkatz commented on src/datatype.c
> +	if (internalLength > 0)
Is this `if` necessary? Based on the last check, `internalLenth` set`

2023-06-23 17:31 UTC, jkatz commented on src/datatype.c
> +		internalLength += VARHDRSZ;
This should provide a comment, e.g. "As a `bytea` is of variable length, we need to allow for the header"

We likely also need a check that `internalLength + VARHDRSZ` is not larger than the varlena max.

2023-06-23 17:31 UTC, jkatz commented on src/datatype.c
> +#endif
This would be easier to read as a macro in compatibility.h:

```c
#if PG_VERSION >= 120000
#define GETSYSCACHEOID2(a,b,c)  GetSysCacheOid2(a, Anum_pg_type_oid, b, c);
#else
#define GETSYSCACHEOID2(a,b,c)  GetSysCacheOid2(a, b, c);
#endif
```

Then the code can become:

```suggestion
	typeOid = GETSYSCACHEOID2(TYPENAMENSP,
							  CStringGetDatum(typeName),
							  ObjectIdGetDatum(typeNamespace));
```

2023-06-23 17:31 UTC, jkatz commented on src/datatype.c
> +		}
If the `if_not_exists` is supposed to fail quietly, the `ereport` won't do that. It will abort the transaction. You just want to return `false`.

2023-06-23 17:31 UTC, jkatz commented on src/datatype.c
> +					 errmsg("type \"%s\" already exists", typeName)));
This is very if/else heavy. Here's an alternative approach:
```suggestion
		if (!moveArrayTypeName(typeOid, typeName, typeNamespace))
		{
		  if (if_not_exists)
		    return false;
		    
		  ereport(NOTICE,
					(errcode(ERRCODE_DUPLICATE_OBJECT),
					 errmsg("type \"%s\" already exists", typeName)));
		}

		typeOid = InvalidOid;
```

2023-06-23 17:31 UTC, jkatz commented on src/datatype.c
> +#if PG_VERSION_NUM >= 140000
I provided an example with a different function in this review. See if that helps.

2023-06-23 17:31 UTC, jkatz commented on src/datatype.c
> +	PG_RETURN_CSTRING(TextDatumGetCString(OidFunctionCall1Coll(output_function, InvalidOid, datum)));
I'd break up this line, in case there are errors on the `OidFunctionCall1Coll` function.

2023-06-23 17:31 UTC, jkatz commented on src/datatype.c
> +							  PROVOLATILE_IMMUTABLE,
Are we validating that the user is providing an immutable function?

2023-06-23 17:31 UTC, jkatz commented on src/datatype.c
> +							  PROPARALLEL_SAFE,
Similarly, are we validating that the user is providing a parallel safe function

2023-06-23 17:31 UTC, jkatz commented on src/datatype.c
> +							ObjectIdGetDatum(funcid));
something seems off with the indentation here.

2023-06-26 21:02 UTC, lyupan commented on src/datatype.c
> +#if PG_VERSION_NUM >= 140000
Done.

2023-06-26 21:03 UTC, lyupan commented on src/datatype.c
> +	if (internalLength > 0)
I think so, because `internalLenth` could be -1 (variable length).

2023-06-26 21:06 UTC, lyupan commented on src/datatype.c
> +		internalLength += VARHDRSZ;
Good catch! I don't see any size check in the postgres for `create type` command, I believe the size restriction is done by defining length as `int16`, I've added the check based on `PG_INT16_MAX`. (i.e. the length has to be le to `PG_INT16_MAX - VARHDRSZ`)

2023-06-26 21:06 UTC, lyupan commented on src/datatype.c
> +#endif
Done. Thanks for the suggestion.

2023-06-26 21:11 UTC, lyupan commented on src/datatype.c
> +		}
I don't think this would abort the transaction, as the report level is `NOTICE`, similarly https://github.com/postgres/postgres/blob/master/src/backend/commands/createas.c#L421

2023-06-26 21:12 UTC, lyupan commented on src/datatype.c
> +					 errmsg("type \"%s\" already exists", typeName)));
Done. Thanks for the suggestion.

2023-06-26 21:12 UTC, lyupan commented on src/datatype.c
> +	PG_RETURN_CSTRING(TextDatumGetCString(OidFunctionCall1Coll(output_function, InvalidOid, datum)));
Done.

2023-06-26 21:16 UTC, lyupan commented on src/datatype.c
> +							  PROVOLATILE_IMMUTABLE,
Good catch. I think we actually should define this attribute based on the user input function; I've changed attributes `prosecdef,  proleakproof, proisstrict, provolatile, proparallel, procost, prorows` to match the actual user input function.

2023-06-26 21:17 UTC, lyupan commented on src/datatype.c
> +							  PROPARALLEL_SAFE,
See previous comment.

2023-06-26 21:17 UTC, lyupan commented on src/datatype.c
> +							ObjectIdGetDatum(funcid));
Done.

2023-06-26 21:19 UTC, lyupan commented
> nice! Would be great to see a page for this in `pgtle/docs` with an example + comparing the `pgtle` functions with equivalent SQL commands. Its clear what's going on from the test suite, but that'll be a little harder for users to track down once merged

Hey Oliver, thanks for the suggestion! The doc is not there yet because the feature is still under development (there will be a few followup changes); once the code changes are mostly completed, we'll add a doc page with examples.

2023-06-29 00:39 UTC, jkatz reviewed
OK,  I think this is pretty close now. My major comment is around turning the `pgtle.create_base_type_if_not_exists` function into a PL/pgSQL function (I provided a reference to a similar one in the comments). This allows us to remove some more C code, and simplifies some of the implementation details in the other functions.

Outside of that, I think this is good to go.

2023-06-29 00:39 UTC, jkatz commented on src/datatype.c
> +		internalLength += VARHDRSZ;
Thanks. In some cases, we need to be more careful in the TLE interface as we're encapsulating functionality of PostgreSQL internals. It's easier for us to start out as more strict and relax later.

2023-06-29 00:39 UTC, jkatz commented on src/datatype.c
> +			}
If we move the `...if_not_exists` to a PL/pgSQL function, we can just return the `ERRCODE_DUPLICATE_OBJECT` and not need this section.

2023-06-29 00:39 UTC, jkatz commented on src/datatype.c
> +static bool
If we move the `if_not_exists` to a PL/pgSQL function, this can become a `static void`

2023-06-29 00:39 UTC, jkatz commented on src/datatype.c
> +	 * way that the I/O functions could have been created.
Personally, when I see I/O, I think filesystem related operations, though I do understand that these are inpout/output functions.

2023-06-29 00:39 UTC, jkatz commented on src/datatype.c
> +		TYPE_CREATE(false,		/* not array type */
Isn't this much easier to read? 😄

2023-06-29 00:39 UTC, jkatz commented on src/datatype.c
> +check_user_input_func(Oid funcid, Oid expectedNamespace)
It looks like the input/output checks are almost identical, subject to a few wording changes. Can we either make the checks a common function, or refactor the code so we only have the check logic once?

For the error message wording, we can say "type function cannot ..." instead of having input/output in it. Or, have a flag that sets the appropriate language of "input" or "output"

2023-06-29 01:13 UTC, JohnHVancouver commented on src/datatype.c
> +	/* As a bytea is of variable length, we need to allow for the header */
Can you add comments on why/how/where you're referencing this from as well

2023-06-29 18:16 UTC, lyupan commented on src/datatype.c
> +check_user_input_func(Oid funcid, Oid expectedNamespace)
Yeah, they are mostly the same, updated to `check_user_defined_func` instead.

2023-06-29 18:17 UTC, lyupan commented on src/datatype.c
> +	 * way that the I/O functions could have been created.
These comments are the same as the postgres source code for create type.

2023-06-29 18:39 UTC, lyupan commented on pg_tle--1.0.4--1.0.5.sql
> +LANGUAGE C;
In the latest commit, only `create_base_type_if_not_exists` is now defined in C, `create_base_type` is defined in `plpgsql` and will raise an exception if `create_base_type_if_not_exists` returns false.

The reason is that there are multiple cases where we could return `ERRCODE_DUPLICATE_OBJECT`, for example, when the shell type doesn't exist when create_baset_type is called (same code as postgres create type).

2023-06-29 18:40 UTC, lyupan commented on src/datatype.c
> +pg_tle_create_base_type_if_not_exists(PG_FUNCTION_ARGS)
See a previous comment

2023-06-29 18:40 UTC, lyupan commented on src/datatype.c
> +			}
see a previous comment

2023-06-29 18:40 UTC, lyupan commented on src/datatype.c
> +static bool
see a previous comment

2023-06-29 18:46 UTC, lyupan commented on src/datatype.c
> +	CommandCounterIncrement();
On a second thought, we don't need this actually https://github.com/postgres/postgres/blob/master/src/backend/access/transam/README#L44. It is already called automatically within a transaction.

We only need it if we want to see the effect within the same command (function), for example, if we want to use one C function to do both create_shell_type and create_base_type.

2023-06-29 18:50 UTC, lyupan commented on src/datatype.c
> +	 * If it's not a shell, see if it's an autogenerated array type, and if so
This part is the same as postgres create type implementation

https://github.com/postgres/postgres/blob/master/src/backend/commands/typecmds.c#L239
https://github.com/postgres/postgres/blob/master/src/backend/commands/typecmds.c#L606

https://www.postgresql.org/docs/current/sql-createtype.html#SQL-CREATETYPE-ARRAY

2023-06-29 18:54 UTC, lyupan commented on src/datatype.c
> +	/* As a bytea is of variable length, we need to allow for the header */
Because we store everything as bytea which has a header, that's why we add it here.

For example, if a client wants to create a fixed length custom type int2: a 2-element vector of one byte integer value; in theory we only need two bytes (if we use `CREATE TYPE` to create it), however, because in the pg_tle implementation, it's stored using bytea, we need to account for the extra header.

2023-06-29 20:15 UTC, jkatz requested changes

2023-06-29 20:15 UTC, jkatz commented on pg_tle--1.0.4--1.0.5.sql
> +$_pgtleie_$
I suggested the opposite -- the C function raises exceptions -- it does not return true/false. Then `pgtle.create_base_type` is a C function.

Then `pgtle.create_base_type_if_not_exists` becomes:

```sql
CREATE FUNCTION pgtle.create_base_type_if_not_exists(
  typenamespace regnamespace,
  typename name,
  infunc regprocedure,
  outfunc regprocedure,
  internallength int4
)
RETURNS bool
LANGUAGE plpgsql
AS $$
BEGIN
  PERFORM pgtle.create_base_type( typenamespace, typename, infunc, outfunc, internallength);
  RETURN TRUE;
EXCEPTION
  -- only catch the unique violation. let all other exceptions pass through.
  WHEN unique_violation THEN
    RETURN FALSE;
END;
$$;
```

2023-06-29 21:07 UTC, lyupan commented on pg_tle--1.0.4--1.0.5.sql
> +$_pgtleie_$
The reason I didn't choose this approach is that there are multiple cases where `create_base_type` could return `ERRCODE_DUPLICATE_OBJECT`.

For example, if `create_base_type` is called without creating shell type first, `ERRCODE_DUPLICATE_OBJECT` is raised (same error in postgres create base type without shell type); then `create_base_type_if_not_exists` would catch this error and return false (it would appear to the user as if the type already exists).

2023-06-29 22:05 UTC, lyupan commented on pg_tle--1.0.4--1.0.5.sql
> +$_pgtleie_$
Updated in the latest commit

2023-06-30 00:20 UTC, jkatz approved these changes

2023-06-30 00:42 UTC, merged