Implement clientauth feature
aws/pg_tle pull request #227
Opened 2023-08-18 19:30 UTC by adamguo0

Issue #, if available:

Description of changes:

Implementation of clientauth feature, allowing users to register trusted language functions to the Postgres ClientAuthentication_hook. Uses background workers to execute database functions.

By submitting this pull request, I confirm that my contribution is made under the terms of the Apache 2.0 license.

2023-08-21 13:31 UTC, adamguo0 commented
I'm doing some load testing by opening a few thousand connections in parallel, and I'm encountering a race condition every few tries that results in the last one or two connections being lost.

My suspicion is that ConditionVariableSleep is not playing well with LWLocks. This is the pattern for waiting on a condition to be true:

```
while (true)
{
    LWLockAcquire(lock);
    if (condition)
    {
        LWLockRelease(lock);
        break;
    }
    // condition not met, now wait for signal
    ConditionVariableSleep(cv);
}
```

Sources that discuss condition variables (e.g. [wikipedia](https://en.wikipedia.org/wiki/Monitor_(synchronization)#Condition_variables_2)) say that LWLockRelease and ConditionVariableSleep must be atomic, or else a race condition can occur where 1. the lock is released, 2. another thread updates the state and sends the signal, and then 3. ConditionVariableSleep is called. This results in a dropped signal. I suspect this is happening because looking at the logs when the dropped connection bug happens, `clientauth_hook` goes to sleep waiting for `processed_entry` to become true, and then never wakes up.

Postgres provides a ConditionVariablePrepareToSleep method which adds a thread to the CV wait list before sleeping so I tried adding that, but the issue isn't fixed. I can't tell if ConditionVariablePrepareToSleep is supposed to handle this case, or if there's something else wrong with the logic? I would appreciate any feedback/advice, thanks!

2023-08-21 22:44 UTC, JohnHVancouver reviewed
>  I can't tell if ConditionVariablePrepareToSleep is supposed to fix this bug or if there's something else wrong with the logic? I would appreciate any feedback/advice, thanks!

The logic seems fine. 
Can you try adding a debug line here:
https://github.com/postgres/postgres/blob/master/src/backend/storage/lmgr/condition_variable.c#L77-L79

Something like logging the MyProcPid (backend_pid) and the CV it's listening on? 

And when BGW signals add logging here:

https://github.com/postgres/postgres/blob/master/src/backend/storage/lmgr/condition_variable.c#L263-L266

To get the signal of the CV, and the PGPROC pid it signals. 

I wonder when the BGW signals the CV, if the client auth backend is actually listening on it?  
Or maybe we have multiple processes listening on the CV, and Signal only signals the oldest, while broadcast does all. 

https://github.com/postgres/postgres/blob/master/src/backend/storage/lmgr/condition_variable.c#L277-L279

Broadcast would be incorrect though cause we're only processing one entry


Also a generic comment on if the client disconnects or client auth backend terminates, do we have a stale shared memory entry perpetually?

2023-08-21 22:44 UTC, JohnHVancouver commented on src/clientauth.c
> +bool can_allow_without_executing(void);
These can be static? (Other than clientauth_init)

2023-08-21 22:44 UTC, JohnHVancouver commented on src/clientauth.c
> +                clientauth_ss->requests[idx].needs_processing = false;
I think one risk you run into with this is that if the BGW is terminated, we would have needs_processing = false even though we haven't actually processed the event. 

I imagine you're doing this to allow parallelization to happen?

2023-08-21 22:44 UTC, JohnHVancouver commented on src/clientauth.c
> +        ConditionVariablePrepareToSleep(&clientauth_ss->requests[idx].client_cv);
OOC is there a reason we put `ConditionVariablePrepareToSleep` within the while loop instead of before?

2023-08-21 22:45 UTC, JohnHVancouver commented on src/clientauth.c
> +        ConditionVariablePrepareToSleep(&clientauth_ss->requests[idx].client_cv);
Also a generic comment on if the client disconnects or client auth backend terminates, do we have a stale shared memory entry then...?

2023-08-22 14:33 UTC, adamguo0 commented on src/clientauth.c
> +        ConditionVariablePrepareToSleep(&clientauth_ss->requests[idx].client_cv);
IIUC ConditionVariablePrepareToSleep adds the thread to CV's queue. I put it in the while loop before LWLockRelease, this way the thread is added to the wait queue before releasing the lock, preventing missed wakeups. Though maybe the thread only needs to be added once per wait loop?

2023-08-22 14:38 UTC, adamguo0 commented on src/clientauth.c
> +bool can_allow_without_executing(void);
Sorry are you asking why they are static or saying that they should be static?

2023-08-22 16:09 UTC, JohnHVancouver commented on src/clientauth.c
> +bool can_allow_without_executing(void);
That they should*

2023-08-22 21:28 UTC, adamguo0 commented
The race condition was caused by an assumption that when `num_requests` is decremented, the next queue entry (denoted by `idx_insert`) would be available. However when a BGW is done processing, we don't know which index it was, chances are it was not the next index in queue. This resulted in entries being clobbered.

This is fixed by adding a flag to each entry denoting whether it is available. This raises two questions though:

1. A long-running query can potentially block all waiting client backends even though latter entries have become available, because client backends look sequentially through the queue
2. This parallelisation approach could cause clobbering issues elsewhere too. Per offline discussion with John we can try partitioning the queue and assigning each entry to a single BGW instead to avoid clobbering.

2023-08-23 21:24 UTC, adamguo0 commented
I pushed a change that assigns each worker a partition of the queue that they are solely responsible for, instead of letting workers pick whatever entry is available for processing. This allows workers terminated mid-process to come back up and resume processing, and gives a stronger guarantee that there is no clobbering between background workers trying to process the same entry.

Rather than inserting sequentially, a client backend decides which queue entry to insert into by calculating `client_backend_pid % number_of_workers`. The PIDs should be roughly sequential which distributes the clients across the BGWs.

However in practice there is some still clustering going on. During load tests, there is a tail of clients that are waiting for the same handful of background workers to process them. We can discuss ways to avoid this or whether we should go back to the original approach.

2023-08-24 01:07 UTC, JohnHVancouver requested changes
> We can discuss ways to avoid this or whether we should go back to the original approach.

I think using rand()  is fineif we've found that PID isn't "sequential" enough that there's still some clustering. 

Although like you mentioned I think the only time this might actually matter is when there's a connection storm such as a connection pool reconnecting and wanting to establish a bunch of new connections, or appservers re-connecting asap after a restart.  One risk we run into is if we're "unlucky" enough we lose the parallelization.

2023-08-24 01:07 UTC, JohnHVancouver commented on src/clientauth.c
> +        proc_names = feature_proc(clientauth_feature);
It's probably too much effort to bother fixing this right now. I think we could probably not have to query this table if we have a trigger on it that calls a pg_tle function to refresh feature_proc

2023-08-24 01:07 UTC, JohnHVancouver commented on src/clientauth.c
> +        elog(LOG, "%s is on pgtle.clientauth_users_to_skip, skipping", port->user_name);
Not sure how I feel about LOG for these vs DEBUG1 (or logging at all) Maybe John/Jonathan has some thoughts here. It's probably useful for auditing?

2023-08-24 01:07 UTC, JohnHVancouver commented on src/clientauth.c
> +    int     idx = MyProc->pid % CLIENT_AUTH_MAX_PENDING_ENTRIES;
Ahh you're %-ing this to get the idx to insert. I guess my earlier comments on fairness doesn't really matter too much? Well it might. 

OOC what were the trade-offs in doing this approach as opposed to something like: 

idx = MyProc % BGW and then start from some idx to try to insert into

2023-08-24 01:07 UTC, JohnHVancouver commented on src/clientauth.c
> +    clientauth_ss->requests[idx].port_info.remote_hostname_resolv = port->remote_hostname_resolv;
I think you should use snprintf for all of these that's char[], not clear to me if you can spoof it even if there's supposed to be restrictions on length.

2023-08-24 01:07 UTC, JohnHVancouver commented on test/t/004_pg_tle_clientauth.pl
> +# Copyright Amazon.com, Inc. or its affiliates. All Rights Reserved.
will review this later

2023-08-24 01:15 UTC, JohnHVancouver commented on test/t/004_pg_tle_clientauth.pl
> +    CREATE FUNCTION reject_testuser(port pgtle.clientauth_port_subset, status integer) RETURNS text AS $$
Also not sure if this should be in the actual code ie. we expect a function with these arguments, or in the docs later

2023-08-24 14:02 UTC, adamguo0 commented on src/clientauth.c
> +                    idx = i;
Yeah, one way to handle the fairness problem could be to process all of that worker's entries instead of just the first one when waking. I'm planning to try that out today

2023-08-24 14:03 UTC, adamguo0 commented on src/clientauth.c
> +        error_msg[0] = 0;
IIUC the integer 0 is the same as the null char \0. but \0 probably makes the intent more clear

2023-08-24 14:12 UTC, adamguo0 commented on src/clientauth.c
> +                if (clientauth_ss->requests[i].needs_processing)
Ah yeah this is old. I meant to get rid of needs_processing after moving to the partitioned scheme. done_processing is sufficient here

2023-08-24 14:15 UTC, adamguo0 commented on Makefile
> +DATA = pg_tle.control pg_tle--1.0.0.sql pg_tle--1.0.0--1.0.1.sql pg_tle--1.0.1--1.0.4.sql pg_tle--1.0.4.sql pg_tle--1.0.4--1.1.1.sql pg_tle--1.1.0--1.1.1.sql pg_tle--1.1.1.sql pg_tle--1.1.1--1.1.2.sq
When we were working on 1.0.4 and 1.1.1, the `pg_tle--$(EXTVERSION).sql` entry meant that `pg_tle--1.0.4.sql` and `pg_tle--1.1.1.sql` were getting deleted whenever I ran make clean which was inconvenient. If that's the goal though (i.e. we don't want standalone sql files for specific versions) then that makes sense

2023-08-24 15:26 UTC, adamguo0 commented on src/clientauth.c
> +    int     idx = MyProc->pid % CLIENT_AUTH_MAX_PENDING_ENTRIES;
I think the fairness comment still applies? The worker will still work on its first entry before moving on to other entries, even if those were filled earlier. If client 1 finishes with entry 1 and signals client 5 to insert, client 5 will get worker priority over clients 2, 3, 4 that occupied the entries 2, 3, 4.

If we put aside the fairness issue (which I think we can resolve by having the worker process all entries per wake or pick entries in a staggered way), I think the two % approaches are the same and we'll observe the same clustering behaviour.

Either the clients will pick distinct entries in the whole queue and then get folded down into BGW buckets, or they'll pick BGW buckets and then spread out across entries in the queue. In the latter approach, clients could in theory find an empty entry earlier instead of having to wait for a single predetermined entry, but since that entry is handled by the same worker anyway it would end up waiting the same amount of time (or at least in aggregate, the total wait time among clients would be the same).

2023-08-24 15:31 UTC, adamguo0 commented on src/clientauth.c
> +    clientauth_ss->requests[idx].port_info.remote_hostname_resolv = port->remote_hostname_resolv;
I think I have snprintf for all the char[] fields -- `noblock` `remote_hostname_resolv` `remote_hostname_errcode` and `status` are ints

2023-08-24 15:58 UTC, adamguo0 commented on src/clientauth.c
> +    worker.bgw_notify_pid = 0;
If the bgw is executing a long query, pg_ctl stop goes through right away and the client connection is closed (and the workers terminate)

2023-08-24 18:41 UTC, adamguo0 commented on src/clientauth.c
> +    BackgroundWorkerInitializeConnection(clientauth_database_name, NULL, 0);
Yeah that's right, I wonder if we could have the client backend could dynamically spin up a background worker instead of signalling one that's just waiting?

2023-08-24 19:45 UTC, adamguo0 commented
Did some testing:

1. Client backend PIDs are actually more uniformly distributed than `rand()`, at least given how I run load tests (which is a lot of `psql -c 'select' &` lines)
2. Workers are not actually picking their first entry significantly more often than their other entries, it's pretty uniform. I added an offset mechanism anyway though in case this does become a problem

2023-08-30 22:53 UTC, JohnHVancouver commented on src/feature.c
> +	bool		skip = false;
nit: spacing? Or is this how pg_indent does it which is weird ehh

s/skip/match ?

2023-08-30 22:53 UTC, JohnHVancouver commented on src/clientauth.c
> + * A connection is successful if any of the following are true: 1. clientauth
Maybe easier to read if it's:

```
are true:

1. ...
2.
3.
4. 
```

2023-08-30 22:53 UTC, JohnHVancouver commented on src/clientauth.c
> +	int			remote_hostname_resolv;
spacing seems a bit off

2023-08-30 22:53 UTC, JohnHVancouver commented on src/clientauth.c
> +	int			status;
similar comment. Maybe pgindent is worst

2023-08-30 22:53 UTC, JohnHVancouver commented on src/clientauth.c
> +							 PGC_SIGHUP,
I would probably make this PGC_POSTMASTER so you can just check below (RegisterBackgroundWorker) if you need to launch the BGWs or not and use restart to gate.  

Kinda adds friction to have to restart but I don't think we should assume people will want this feature "laying" around even if it's doing "nothing"

2023-08-30 22:53 UTC, JohnHVancouver commented on src/clientauth.c
> +/* Run the user's functions. This procedure should not do any transaction
nit:  add line break?

2023-08-30 22:53 UTC, JohnHVancouver commented on src/clientauth.c
> +		StartTransactionCommand();
OOC do we need to do this or does SPI_exec handle that? I'm not as familiar with the StartTransaction // why we need to explicitly Begin a SubTransaction below

2023-08-30 22:53 UTC, JohnHVancouver commented on src/clientauth.c
> +		clientauth_ss->requests[idx].done_processing = true;
I think you should move `done_processing` to the very end in case BGW gets terminated in between?

2023-08-30 22:53 UTC, JohnHVancouver commented on src/clientauth.c
> +	clientauth_ss->requests[idx].available_entry = true;
I think I brought this up earlier in a comment. 

> Also a generic comment on if the client disconnects or client auth backend terminates, do we have a stale shared memory entry perpetually?

So I think you're fine in the case of a BGW terminates because you'll restart and work on the entry again as long as `done_processing` is not set too early. 

One issue if the ClientBackend drops/terminates is that the entry never gets cleaned up?

2023-08-30 22:53 UTC, JohnHVancouver commented on src/clientauth.c
> + * A connection is successful if any of the following are true: 1. clientauth
repeats elsewhere

2023-08-30 23:25 UTC, adamguo0 commented on src/feature.c
> +	bool		skip = false;
Ah thanks for catching that, yeah pg_indent likes to do this apparently

2023-08-30 23:25 UTC, adamguo0 commented on src/clientauth.c
> + * A connection is successful if any of the following are true: 1. clientauth
this is pg_indent's work again.. I have to put two line breaks or else it combines the lines

2023-08-30 23:31 UTC, adamguo0 commented on src/clientauth.c
> +		StartTransactionCommand();
The subtransaction is used so we can have logic that handles SPI errors https://postgrespro.com/list/thread-id/1881982, I saw StartTransaction used in other BGW examples that do DB accesses

2023-08-31 14:18 UTC, adamguo0 commented on src/clientauth.c
> +	int			remote_hostname_resolv;
I think pg_indent is assuming 4 character tabs but github is rendering 8 character tabs which makes it look weird

2023-08-31 14:21 UTC, adamguo0 commented on src/clientauth.c
> +							 PGC_SIGHUP,
Ahh that makes a lot of sense, thanks for the suggestion

2023-09-05 16:01 UTC, adamguo0 commented
Pushed a fix for the stale entry bug. Copying the commit message here:
```
If a client backend terminates unexpectedly after setting
entry_available = false, it can block every subsequent client from using
that entry.

This commit adds a PID field to the request entry struct and allows
clients to check if the process currently holding the entry still
exists. If it doesn't, then it can set entry_available to true.

Signalling order is rearranged to prevent deadlocks where a backend is
terminated after entry_available is set to false but before signalling
anyone else. In addition to signalling the current client, background
workers signal the next waiting client to check if the current client
still exists.
```
I tested this by setting CLIENT_AUTH_MAX_PENDING_ENTRIES to 1, starting a connection and SIGTERMing it, then starting another connection. Previously the second connection would be blocked forever, now it goes through as expected.

2023-09-05 21:20 UTC, JohnHVancouver commented on src/clientauth.c
> +	if (IsBinaryUpgrade)
Can remove this in favor of moving IsBinaryUpgrade up to ClintAuthInit beginning

2023-09-05 21:20 UTC, JohnHVancouver commented on src/clientauth.c
> +		if (!BackendPidGetProc(clientauth_ss->requests[idx].pid))
The reason this works is because MyBackendPid always goes to the same requests[idx] right. 

If the BackendPid has been properly authenticated, we don't need to worry about the entry ever being stale. If it doesn't exist, then the entry is by definition stale and we reset when the Client needs to use it

2023-09-05 21:20 UTC, JohnHVancouver commented on src/clientauth.c
> +	 * terminates after grabbing the entry but before signalling anybody.
It's not clear to me why we deadlock. It seems to imply that if the backend terminates on line 674 we're still stuck which shouldn't be true?

2023-09-05 21:23 UTC, adamguo0 commented on src/clientauth.c
> +		CommitTransactionCommand();
Yeah I think we need to be able to commit writes here. Good point on the warning, we should make it clear that these queries just run as superuser too

2023-09-06 00:03 UTC, adamguo0 commented on src/clientauth.c
> +	 * terminates after grabbing the entry but before signalling anybody.
It's not really a deadlock actually, it's more that if the backend terminates on line 674 then the BGW and the next backend will be waiting indefinitely for someone to signal them. If one of them wakes up then we can proceed as normal.

In testing it seemed like the next backend actually gets woken up when the first backend terminates? I'm not sure how

2023-09-06 00:05 UTC, adamguo0 commented on src/clientauth.c
> +	 * Don't start the background workers if we are in pg_upgrade either.
Makes sense, IIUC it should be before the hooks and after the GUC inits?

2023-09-06 00:11 UTC, adamguo0 commented on src/clientauth.c
> +		 * Look at the first item of the first row for the return value. If
Working on documentation and planning to open another PR for it

2023-09-06 18:03 UTC, JohnHVancouver commented on src/clientauth.c
> +	 * terminates after grabbing the entry but before signalling anybody.
Is this testing the case where there's only one entry? 

IIUC:

BGW loops through everything until it finds nothing to then sleeps
A new backend connection that hashes to a different bucket would always signal?

2023-09-06 18:31 UTC, JohnHVancouver commented on src/clientauth.c
> +	 * terminates after grabbing the entry but before signalling anybody.
Yea I think we are. There's a minor chance due to lock acquisition order we get a stuck backend but there is `authentication_timeout ` for those cases.

2023-09-06 19:40 UTC, JohnHVancouver commented on src/clientauth.c
> +	 * terminates after grabbing the entry but before signalling anybody.
We should update the comment fwiw

2023-09-06 23:54 UTC, JohnHVancouver commented on src/clientauth.c
> +		SPI_execute_with_args(query, SPI_NARGS_2, hookargtypes, hookargs, hooknulls, true, 0);
I think we should check the return value here too? Might not be necessary but what do you think

https://www.postgresql.org/docs/current/spi-spi-execute-with-args.html
https://www.postgresql.org/docs/current/spi-spi-execute.html

2023-09-06 23:54 UTC, JohnHVancouver commented on src/clientauth.c
> +		ConditionVariableSleep(clientauth_ss->requests[idx].available_entry_cv_ptr, WAIT_EVENT_MESSAGE_QUEUE_RECEIVE);
I guess this can potentially be race-y? However unlikely it is considering BGW needs to write a bunch of things into mem

2023-09-06 23:54 UTC, JohnHVancouver commented on src/clientauth.c
> +	if (can_allow_without_executing())
If a customer has both 'require' and database_skip/user_skip configured it'll go through right. We prioritize one over the error

2023-09-07 00:00 UTC, adamguo0 commented on src/clientauth.c
> +	if (can_allow_without_executing())
I think it makes sense for databases and users on the skip list to be allowed through if `require` is set, it can be an escape hatch if the user has locked themselves out with `require`. imo being on the skip list should mean clientauth doesn't do anything to you

2023-09-07 00:02 UTC, adamguo0 commented on src/clientauth.c
> +		ConditionVariableSleep(clientauth_ss->requests[idx].available_entry_cv_ptr, WAIT_EVENT_MESSAGE_QUEUE_RECEIVE);
Do you mean if BGW signals between lines 663 and 664? IIUC `ConditionVariablePrepareToSleep` adds you to the CV queue, so if BGW signals before line 664 then ConditionVariableSleep will "wake immediately".

https://github.com/postgres/postgres/blob/8c16ad3b43299695f203f9157a2b27c22b9ed634/src/backend/storage/lmgr/condition_variable.c#L76

2023-09-07 00:09 UTC, adamguo0 commented on src/clientauth.c
> +		SPI_execute_with_args(query, SPI_NARGS_2, hookargtypes, hookargs, hooknulls, true, 0);
Yeah makes sense, adding the same handling as in passcheck

2023-09-07 16:06 UTC, JohnHVancouver commented on src/clientauth.c
> +		SPI_execute_with_args(query, SPI_NARGS_2, hookargtypes, hookargs, hooknulls, true, 0);
Is it always `SPI_SELECT` even if an INSERT was done by the function? 

ie. we do something like

SELECT * FROM insert_foo();

2023-09-07 16:07 UTC, JohnHVancouver commented on src/clientauth.c
> +		ConditionVariableSleep(clientauth_ss->requests[idx].available_entry_cv_ptr, WAIT_EVENT_MESSAGE_QUEUE_RECEIVE);
Wait nevermind there's the lock still which is LW_EXCLUSIVE

2023-09-07 16:13 UTC, adamguo0 commented on src/clientauth.c
> +		SPI_execute_with_args(query, SPI_NARGS_2, hookargtypes, hookargs, hooknulls, true, 0);
I think it is but not sure I can guarantee that, checking < 0 also makes sense

2023-09-07 16:16 UTC, adamguo0 commented on src/clientauth.c
> +		SPI_execute_with_args(query, SPI_NARGS_2, hookargtypes, hookargs, hooknulls, true, 0);
Tested with INSERT and it does return SPI_OK_SELECT -- we also use the same logic in passcheck

2023-09-07 16:18 UTC, JohnHVancouver commented on include/compatibility.h
> +#define WAIT_EVENT_MESSAGE_QUEUE_RECEIVE WAIT_EVENT_MQ_RECEIVE
This one's duplicated, and we're only using one right might not need to declare all

2023-09-07 16:24 UTC, JohnHVancouver approved these changes

2023-09-07 16:39 UTC, merged