Add uuid v7 example
aws/pg_tle pull request #242
Opened 2023-11-10 21:04 UTC by anth0nyleung

### Add an example to create a uuid v7 extension

Description of changes:

This adds an example to demonstrate how to create a Trusted Language Extension for uuid v7.

By submitting this pull request, I confirm that my contribution is made under the terms of the Apache 2.0 license.

2023-11-13 16:41 UTC, adamguo0 commented on examples/uuid_v7/uuid_v7.sql
> +            Ok(Some(Uuid::from_bytes(generate_uuid_v7_bytes())))
Does `Uuid` refer to the Rust uuid crate? I notice uuid is not listed as a dependency above

2023-11-13 16:41 UTC, adamguo0 commented on examples/uuid_v7/uuid_v7.sql
> +            fn generate_uuid_bytes_from_fields(d1: u32, d2: u16, d3: u16, d4: &[u8; 8]) -> UuidBytes {
IIUC once this feature is added to pgrx https://github.com/tcdi/plrust/issues/370, we would be able to remove these duplicated function definitions?

2023-11-13 16:47 UTC, anth0nyleung commented on examples/uuid_v7/uuid_v7.sql
> +            fn generate_uuid_bytes_from_fields(d1: u32, d2: u16, d3: u16, d4: &[u8; 8]) -> UuidBytes {
That's correct. upstream is still working on releasing that feature. But once the feature is released, we can duplicate less code.

2023-11-13 16:47 UTC, anth0nyleung commented on examples/uuid_v7/uuid_v7.sql
> +            Ok(Some(Uuid::from_bytes(generate_uuid_v7_bytes())))
This is the `Uuid` api from `plrust-trusted-pgrx` - https://docs.rs/plrust-trusted-pgrx/latest/plrust_trusted_pgrx/datum/struct.Uuid.html. 

If we were using the uuid-rs crate, then we'll have to declare it in the `[dependencies]` section which is not the case here.

2023-11-13 17:13 UTC, adamguo0 approved these changes

2023-11-15 18:49 UTC, jeff-davis reviewed
Have you considered using endian conversions rather than manually moving bytes around?

2023-11-15 18:49 UTC, jeff-davis commented on examples/uuid_v7/uuid_v7.sql
> +    CREATE FUNCTION generate_uuid_v7()
Comment to explain generation (e.g. "epoch in milliseconds converted to int in BE format")

2023-11-15 18:49 UTC, jeff-davis commented on examples/uuid_v7/uuid_v7.sql
> +    CREATE FUNCTION uuid_v7_to_timestamptz(uuid UUID)
Explain format.

2023-11-15 18:49 UTC, jeff-davis commented on examples/uuid_v7/uuid_v7.sql
> +    CREATE FUNCTION timestamptz_to_uuid_v7(tz timestamptz)
Explain format. If truncation of some microseconds happens, explain that two different timestamps can get the same UUID.

2023-11-15 18:50 UTC, jeff-davis commented on examples/uuid_v7/uuid_v7.sql
> +            let micros = millis as f64 / 1000 as f64;
Explain conversion to `f64`.

2023-11-15 21:43 UTC, samimseih commented on examples/uuid_v7/README.md
> +CREATE EXTENSION
CREATE EXTENSION should be part of the uuid_v7.sql script for simplicity and the user will expect everything to just be ready once they run the sql script.

2023-11-15 21:46 UTC, samimseih commented on examples/uuid_v7/README.md
> +   uuid_v7_to_timestamptz
in line 29, can you do ```SELECT generate_uuid_v7(), now() as timestamp;``` so by the time the user reads down here, they can see the timestamp returned matches.

2023-11-16 04:14 UTC, samimseih commented on examples/uuid_v7/uuid_v7.sql
> +    STRICT IMMUTABLE;
The function should be marked as VOLATILE

2023-11-16 04:21 UTC, samimseih commented on examples/uuid_v7/uuid_v7.sql
> +    STRICT IMMUTABLE;
This should be VOLATILE as well. See comment above.

2023-11-20 17:50 UTC, anth0nyleung commented on examples/uuid_v7/README.md
> +   uuid_v7_to_timestamptz
The timestamp would not match exactly because of precision. Uuidv7 only needs up to millisecond but `now()` tracks up to microseconds.
```
postgres=# SELECT generate_uuid_v7(), now() as timestamp;
           generate_uuid_v7           |           timestamp
--------------------------------------+-------------------------------
 018bd546-3fef-7739-9d46-c7320a6291fc | 2023-11-15 18:17:12.814624-05
(1 row)

postgres=# SELECT uuid_v7_to_timestamptz('018bd546-3fef-7739-9d46-c7320a6291fc');
   uuid_v7_to_timestamptz
----------------------------
 2023-11-15 18:17:12.815-05
(1 row)
```

But using [pg_uuidv7](https://github.com/fboulnois/pg_uuidv7) as a reference,
```sql
-- pg_uuidv7
postgres=# select now() as a, uuid_generate_v7() as b \gset
postgres=# select uuid_v7_to_timestamptz(:'b'), :'a';
   uuid_v7_to_timestamptz   |           ?column?
----------------------------+-------------------------------
 2023-11-20 12:13:02.575-05 | 2023-11-20 12:13:02.574888-05
(1 row)
```

my example behaving in the same fashion. 
```sql
postgres=# select now() as a, generate_uuid_v7() as b \gset
postgres=# select uuid_v7_to_timestamptz(:'b'), :'a';
   uuid_v7_to_timestamptz   |           ?column?
----------------------------+-------------------------------
 2023-11-20 12:44:34.314-05 | 2023-11-20 12:44:34.190486-05
(1 row)
```

2023-11-20 17:53 UTC, anth0nyleung commented on examples/uuid_v7/uuid_v7.sql
> +    CREATE FUNCTION timestamptz_to_uuid_v7(tz timestamptz)
Unless i'm misunderstanding something - If truncation of some microseconds happens, i believe the uuid would still be different because the random bits would not be the same.

2023-11-29 15:02 UTC, jkatz requested changes

2023-11-29 15:02 UTC, jkatz commented on examples/uuid_v7/README.md
> +```
Do we also want to show the code that's inside the extension by having the code in the documentation? That will simplify cutting and pasting.

Additionally, where can the reader find the `uuid_v7.sql` file?

2023-11-29 15:02 UTC, jkatz commented on examples/uuid_v7/README.md
> +To generate a v7 uuid
```suggestion
To generate a UUID using UUID v7, you can run the following command:
```

2023-11-29 15:02 UTC, jkatz commented on examples/uuid_v7/README.md
> +Newly generated v7 uuid is older than ones generated previously
```suggestion
You can verify that a more recently generated UUID v7 used a newer timestamp than a previously generated UUID v7:
```

2023-11-29 15:02 UTC, jkatz commented on examples/uuid_v7/README.md
> +To generate a v7 uuid with a given timestamp
```suggestion
The generate a UUID using UUID v7, you can run the following command:
```

2023-11-29 15:02 UTC, jkatz commented on examples/uuid_v7/README.md
> +The extracted timestamp from the uuid is the same as the timestamp that was given to generate the uuid
```suggestion
You can verify that the timestamp that you used to generate the UUID v7 matches the one that you provided:
```

2023-11-29 18:58 UTC, adamguo0 commented on examples/uuid_v7/README.md
> +To extract the timestamp from the v7 uuid. Note that since UUID v7 uses millisecond level of precision, the returns timestamp
Incomplete sentence?

2023-11-29 23:30 UTC, jkatz commented on examples/uuid_v7/README.md
> +To install the extension, run the `uuid_v7.sql` file in the desired database
We should link to the file so the reader is able to find the code quickly.

2023-11-29 23:34 UTC, jkatz requested changes

2023-11-29 23:34 UTC, jkatz commented on examples/uuid_v7/README.md
> +To uninstall the extension
```suggestion
You can uninstall the extension using the following commands:
```

2023-11-29 23:34 UTC, jkatz commented on examples/uuid_v7/README.md
> +postgres=# SELECT generate_uuid_v7();
Remove the `postgres=#` from all of the examples. This makes it challening to copy and paste the code.

2023-12-04 21:14 UTC, jkatz commented on examples/uuid_v7/uuid_v7.sql
> +    STRICT IMMUTABLE;
This still needs the volatility change.

2023-12-04 21:15 UTC, jkatz reviewed
Generally LGTM, outside of one small comment.

2023-12-05 01:45 UTC, jkatz approved these changes

2023-12-05 01:45 UTC, merged